apiVersion: v1
kind: Pod
metadata:
  name: test-eso
spec:
  containers:
    - name: test-eso
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - secretRef:
          name: redis-creds
