apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-creds
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: redis-creds
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: redis-creds
